"""
Record objects for storing information about the MARS fitting process.

This can include details about the forward pass (terms added, RSS at each step)
and the pruning pass (terms removed, GCV at each step).
"""

from __future__ import annotations

import logging
from typing import Any

import numpy as np

logger = logging.getLogger(__name__)

from ._basis import BasisFunction


class EarthRecord:
    """
    Stores information about the fitting process of an Earth model.
    """

    def __init__(self, X: np.ndarray, y: np.ndarray, earth_model_instance: Any):
        del y
        self.model_params: dict[str, Any] = (
            earth_model_instance.__dict__.copy()
        )  # Store initial model params
        self.n_samples = X.shape[0]
        self.n_features = X.shape[1]

        # Forward pass tracking
        self.fwd_basis_: list[
            list[BasisFunction]
        ] = []  # List of lists: basis functions at each step of fwd pass
        self.fwd_coeffs_: list[
            np.ndarray
        ] = []  # List of arrays: coefficients at each step
        self.fwd_rss_: list[float] = []  # List of floats: RSS at each step

        # Pruning pass tracking
        # These will store the sequence of models considered during pruning.
        # Each element corresponds to a model of a certain size.
        self.pruning_trace_basis_functions_: list[list[BasisFunction]] = []
        self.pruning_trace_coeffs_: list[np.ndarray] = []
        self.pruning_trace_gcv_: list[float] = []
        self.pruning_trace_rss_: list[float] = []

        # Final selected model details (can be set after pruning)
        self.final_basis_: list[BasisFunction] | None = None
        self.final_coeffs_: np.ndarray | None = None
        self.final_gcv_: float | None = None
        self.final_rss_: float | None = None
        self.final_mse_: float | None = None  # MSE of the final model on training data

    def log_forward_pass_step(
        self, basis_functions: list[BasisFunction], coefficients: np.ndarray, rss: float
    ) -> None:
        """Log a step in the forward pass."""
        self.fwd_basis_.append(list(basis_functions))  # Store copies
        self.fwd_coeffs_.append(np.copy(coefficients))
        self.fwd_rss_.append(rss)

    def log_pruning_step(
        self,
        basis_functions: list[BasisFunction],
        coefficients: np.ndarray,
        gcv: float,
        rss: float,
    ) -> None:  # Renamed
        """
        Log a model state (basis functions, coefficients, GCV, RSS) encountered
        during the pruning pass sequence. This is typically called for each model size
        generated by removing one term at a time.
        """
        logger.debug(
            "Logging pruning step. Num basis functions: %d, GCV: %.4f",
            len(basis_functions),
            gcv,
        )
        self.pruning_trace_basis_functions_.append(
            list(basis_functions)
        )  # Store copies
        self.pruning_trace_coeffs_.append(np.copy(coefficients))
        self.pruning_trace_gcv_.append(gcv)
        self.pruning_trace_rss_.append(rss)

    def set_final_model(
        self,
        basis_functions: list[BasisFunction],
        coefficients: np.ndarray,
        gcv: float,
        rss: float,
        mse: float,
    ) -> None:
        """Set the details of the final pruned model."""
        self.final_basis_ = list(basis_functions)
        self.final_coeffs_ = np.copy(coefficients)
        self.final_gcv_ = gcv
        self.final_rss_ = rss
        self.final_mse_ = mse

    def __str__(self) -> str:
        summary = ["Earth Model Fit Record"]
        summary.append("=" * len(summary[0]))
        summary.append(
            f"Initial Samples: {self.n_samples}, Features: {self.n_features}"
        )

        if self.fwd_rss_:
            summary.append(
                f"\nForward Pass completed with {len(self.fwd_basis_[-1])} terms."
            )
            summary.append(f"  Final RSS from forward pass: {self.fwd_rss_[-1]:.4f}")

        if self.pruning_trace_gcv_:
            summary.append(
                f"\nPruning Pass Trace (models considered): {len(self.pruning_trace_gcv_)}"
            )
            # Optionally print details of the trace, e.g., GCVs
            # summary.append(f"  GCVs in sequence: {[f'{g:.4f}' for g in self.pruning_trace_gcv_]}")

        if self.final_basis_ is not None:
            summary.append("\nFinal Selected Model (after pruning):")
            summary.append(f"  Number of terms: {len(self.final_basis_)}")
            summary.append(f"  GCV: {self.final_gcv_:.4f}")
            summary.append(f"  RSS: {self.final_rss_:.4f}")
            summary.append(f"  MSE: {self.final_mse_:.4f}")

        return "\n".join(summary)
